CREATE TABLE "guest_usage_meter_monthly" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guest_usage_meter_monthly_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guest_id" text NOT NULL,
	"month_key" text NOT NULL,
	"processed_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "guest_usage_meter_monthly_guest_month_unique" ON "guest_usage_meter_monthly" USING btree ("guest_id","month_key");