CREATE TABLE "organization" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organization_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role" text DEFAULT 'owner' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organization_invite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_invite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"email" text NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"token" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"expires_at" timestamp with time zone,
	"accepted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "receipt_activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "receipt_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" text NOT NULL,
	"receipt_id" text NOT NULL,
	"actor_user_id" text,
	"action" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "billing_customer" ADD COLUMN "organization_id" text;--> statement-breakpoint
ALTER TABLE "usage_meter_monthly" ADD COLUMN "organization_id" text;--> statement-breakpoint
ALTER TABLE "receipt" ADD COLUMN "organization_id" text;--> statement-breakpoint
ALTER TABLE "receipt" ADD COLUMN "reviewed_by_user_id" text;--> statement-breakpoint
ALTER TABLE "receipt" ADD COLUMN "posted_by_user_id" text;--> statement-breakpoint
ALTER TABLE "organization_member" ADD CONSTRAINT "organization_member_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_member" ADD CONSTRAINT "organization_member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_invite" ADD CONSTRAINT "organization_invite_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_activity" ADD CONSTRAINT "receipt_activity_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_activity" ADD CONSTRAINT "receipt_activity_receipt_id_receipt_id_fk" FOREIGN KEY ("receipt_id") REFERENCES "public"."receipt"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt_activity" ADD CONSTRAINT "receipt_activity_actor_user_id_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "billing_customer" ADD CONSTRAINT "billing_customer_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usage_meter_monthly" ADD CONSTRAINT "usage_meter_monthly_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt" ADD CONSTRAINT "receipt_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt" ADD CONSTRAINT "receipt_reviewed_by_user_id_user_id_fk" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "receipt" ADD CONSTRAINT "receipt_posted_by_user_id_user_id_fk" FOREIGN KEY ("posted_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "organization_slug_unique" ON "organization" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "organization_member_org_user_unique" ON "organization_member" USING btree ("organization_id","user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "organization_invite_token_unique" ON "organization_invite" USING btree ("token");--> statement-breakpoint
CREATE UNIQUE INDEX "billing_customer_org_id_unique" ON "billing_customer" USING btree ("organization_id");--> statement-breakpoint
CREATE UNIQUE INDEX "usage_meter_monthly_org_month_unique" ON "usage_meter_monthly" USING btree ("organization_id","month_key");--> statement-breakpoint
CREATE UNIQUE INDEX "receipt_id_org_unique" ON "receipt" USING btree ("organization_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "receipt_org_hash_unique" ON "receipt" USING btree ("organization_id","source_file_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "receipt_org_fingerprint_unique" ON "receipt" USING btree ("organization_id","receipt_fingerprint");--> statement-breakpoint

INSERT INTO "organization" ("id", "name", "slug", "created_at", "updated_at")
SELECT
	'user-org:' || "id",
	CASE
		WHEN trim("name") = '' THEN 'Workspace'
		ELSE trim("name") || ' Workspace'
	END,
	'user-org-' || "id",
	"created_at",
	"updated_at"
FROM "user"
ON CONFLICT ("id") DO NOTHING;
--> statement-breakpoint

INSERT INTO "organization_member" ("organization_id", "user_id", "role", "status", "created_at", "updated_at")
SELECT
	'user-org:' || "id",
	"id",
	'owner',
	'active',
	"created_at",
	"updated_at"
FROM "user"
ON CONFLICT ("organization_id", "user_id") DO NOTHING;
--> statement-breakpoint

UPDATE "billing_customer"
SET "organization_id" = 'user-org:' || "user_id"
WHERE "organization_id" IS NULL;
--> statement-breakpoint

UPDATE "usage_meter_monthly"
SET "organization_id" = 'user-org:' || "user_id"
WHERE "organization_id" IS NULL;
--> statement-breakpoint

UPDATE "receipt"
SET
	"organization_id" = 'user-org:' || "user_id",
	"reviewed_by_user_id" = CASE
		WHEN "review_status" = 'reviewed' THEN "user_id"
		ELSE NULL
	END,
	"posted_by_user_id" = CASE
		WHEN "review_status" = 'posted' THEN "user_id"
		ELSE NULL
	END
WHERE "organization_id" IS NULL;
